# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20170129_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
